spring:
  application:
    name: USER-SERVICE
  # profile:
  #   active: dev
  cloud:
    config:
      name: user-service
      uri: http://configuration-server:8888
  config:      
   import: "optional:configserver:"
